apiVersion: apps/v1
kind: Deployment
metadata:
  name: securepolicy-api
  namespace: securepolicy
  labels:
    app: securepolicy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: securepolicy-api
  template:
    metadata:
      labels:
        app: securepolicy-api
    spec:
      containers:
        - name: api
          image: __BACKEND_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: h2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: securepolicy-api
  namespace: securepolicy
spec:
  type: ClusterIP
  selector:
    app: securepolicy-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
